# Generated by Django 2.1.4 on 2018-12-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20181218_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived'), ('removed_by_user', 'removed_by_user'), ('removed_by_admin', 'removed_by_admin'), ('removed_automatically', 'removed_automatically')], default='active', max_length=32),
        ),
    ]
