# Generated by Django 2.0.3 on 2018-03-28 03:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_framework_apicontrol', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_apicontrol.App')),
            ],
        ),
        migrations.CreateModel(
            name='PlanGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_apicontrol.App')),
            ],
        ),
        migrations.CreateModel(
            name='PlanInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('renewal_datetime', models.DateTimeField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenewalOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('discount', models.FloatField(default=0)),
                ('renewal_period_count', models.IntegerField(default=1)),
                ('renewal_period_type', models.CharField(choices=[('hours', 'hours'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='months', max_length=12)),
                ('plan_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.PlanGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='plangroup',
            unique_together={('code', 'app')},
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('code', 'app')},
        ),
    ]
