# Generated by Django 2.1 on 2018-10-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20180414_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewaloption',
            name='plan_group',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
