# Generated by Django 2.1 on 2018-10-10 02:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_renewal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planinstance',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
