# Generated by Django 2.1 on 2018-10-10 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181010_0233'),
        ('plans', '0007_auto_20181010_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinstance',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
            preserve_default=False,
        ),
    ]
