# Generated by Django 2.1.4 on 2018-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_create_default_renewal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinstance',
            name='instance_status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived'), ('removed_by_user', 'removed_by_user'), ('removed_by_admin', 'removed_by_admin'), ('removed_automatically', 'removed_automatically')], default='active', max_length=32),
        ),
    ]
