# Generated by Django 2.1 on 2018-10-10 02:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181010_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
