# Generated by Django 2.1.4 on 2018-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181010_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived'), ('removed_by_user', 'removed_by_user'), ('removed_by_admin', 'removed_by_admin'), ('removed_automatically', 'removed_automatically')], default='active', max_length=32),
        ),
    ]
