# Generated by Django 2.0.3 on 2018-03-31 06:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_apicontrol', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('stock', models.IntegerField()),
                ('valid_to', models.DateTimeField(default=django.utils.timezone.now, help_text="Limit DateTime in which the Stock instance 'll be valid.")),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_apicontrol.App')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductVariant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product_variant', 'app')},
        ),
    ]
